language: python
dist: xenial
sudo: required
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=">=1.11,<2.0"
  - DJANGO_VERSION=">=2.0,<2.1"
  - DJANGO_VERSION=">=2.1,<2.2"
matrix:
  exclude:
    - env: DJANGO_VERSION=">=2.0,<2.1"
      python: "2.7"
    - env: DJANGO_VERSION=">=2.1,<2.2"
      python: "2.7"
    - env: DJANGO_VERSION=">=1.11,<2.0"
      python: "3.7"
addons:
  chrome: stable
  apt:
    packages:
    - enchant
before_install:
  - pip install codecov
  - wget https://chromedriver.storage.googleapis.com/2.36/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
install:
  - pip install -q -r test_requirements.txt
  - pip install -q Django$DJANGO_VERSION
script:
#  - python setup.py install
  - coverage run manage.py test test_tinymce
after_success:
 - codecov
before_deploy: wget https://raw.githubusercontent.com/romanvm/travis_scripts/master/publish_docs.py
deploy:
  - provider: script
    script: python publish_docs.py
    skip_cleanup: true
    on:
      branch: master
      python: "3.7"
      condition: $DJANGO_VERSION = ">=2.1,<2.2"
  - provider: pypi
    skip_cleanup: true
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      python: "3.7"
      condition: $DJANGO_VERSION = ">=2.1,<2.2"
notifications:
  email: false
