language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.13
  - DJANGO_VERSION=1.9.6
  - DJANGO_VERSION=1.10.2
addons:
  apt:
    packages:
     - enchant
before_install:
  - pip install codecov
install:
  - pip install -q -r test_requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script:
  - python setup.py build
  - coverage run manage.py test test_tinymce
after_success:
 - codecov
before_deploy: wget https://raw.githubusercontent.com/romanvm/travis_scripts/master/publish_docs.py
deploy:
  - provider: script
    script: python publish_docs.py
    skip_cleanup: true
    on:
      branch: master
      python: "3.5"
      condition: "$DJANGO_VERSION = 1.10.2"
  - provider: pypi
    skip_cleanup: true
    user: $PYPI_USER
    password: $PYPI_PASS
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      python: "3.5"
      condition: "$DJANGO_VERSION = 1.10.2"
notifications:
  email: false
