language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.9
  - DJANGO_VERSION=1.9.2
addons:
  apt:
    packages:
     - enchant
before_install:
  - pip install codecov
install:
  - pip install -q -r test_requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script: coverage run manage.py test test_tinymce
after_success:
 - codecov
deploy:
  provider: script
  script: python publish_docs.py
  skip_cleanup: true
  on:
    tags: true
